<a href="https://colab.research.google.com/github/Baldros/Supervisioned-Learning/blob/main/Introdu%C3%A7%C3%A3oaoPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Apresentação:

    Codigo construido para começar a estudar o processo de construção
    de redes neurais utilizando a biblioteca pytorch.

    O PyTorch é uma biblioteca de código aberto para aprendizado
    profundo (deep learning) em Python desenvolvida pelo Facebook
    AI Research (FAIR) e lançado em 2016. Ele oferece tensores dinâmicos,
    facilitando a construção e treinamento de redes neurais.






In [ ]:
import torch
import numpy as np

# Introdução - tensores vs arrays(numpy):

    Tensores arrays (numpy) tem muito em comum.
    Ambas são representação de objetos matemáticos
    da algebra linear, ou seja, aqui estamos trabalhando
    com matrizes.

    Arrays numpy possuem algumas vantagens com relação
    ao desempenho na hora de se fazer calculos matriciais.
    Os tensores possuem algumas vantagens na hora de se
    fazer calculos matriciais para as redes neurais.

    Resumidamente, tensores e arrays tratam do mesmo
    objeto matemático, matrizes, porêm em contextos
    computacionais diferentes.

In [ ]:
# Exemplo 1:
array = [1,2,3],[4,5,6]
tensor = torch.tensor(array)

In [ ]:
# Exemplo 2:
np_array = np.array(array)
np_tensor = torch.from_numpy(np_array)

    Como arrays numpy, tensores são multidimensionais,
    representando uma coleção de elementos
    dispostos em uma grade com multiplas dimensões.

In [ ]:
tensor.shape

torch.Size([2, 3])

In [ ]:
tensor.dtype

torch.int64

In [ ]:
tensor.device

device(type='cpu')

    Note que esse método um array numpy não possui,
    porque não faz muito sentido para o contexto do numpy
    saber esse tipo de coisa.
    
    Já no contexto de redes neurais, isso é um conhecimento
    interessante. Entende a diferença? Está nos detalhes.
    Você consegue fazer redes de aprendizado profundo com
    numpy, mas o pytorch já da mais informações de forma mais
    mastigada.

    Aprendizado profundo geralmente requer uma GPU, que,
    comparada a CPU pode oferecer recursos de computação
    paralela, tempos de treinamento mais rápidos e melhor
    desempenho.

In [ ]:
print(tensor)
print(tensor.T)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


# Construindo uma Rede Neural:

## T1

In [ ]:
import torch.nn as nn

In [ ]:
# Construindo a camada de entrada:
input_tensor = torch.tensor(
    [[0.3471,0.4547,0.-2356]]
)

    Aqui temos um tensor com três neurônios.

In [ ]:
# Definindo a camada linear:
linear_layer = nn.Linear(in_features=3,out_features=2)

    Uma camada linear pega um tensor de entrada, aplica a
    função linear a ele e retorna uma saída.

In [ ]:
# Gerando a saída:
output = linear_layer(input_tensor);output

tensor([[-867.2303, 1338.0869]], grad_fn=<AddmmBackward0>)

In [ ]:
array = np.array([[0.3471,0.4547,0.-2356]])

## T2

In [ ]:
model = nn.Sequential(
    nn.Linear(10,18),
    nn.Linear(18,20),
    nn.Linear(20,5)
)

In [ ]:
print(input_tensor)

tensor([[ 3.4710e-01,  4.5470e-01, -2.3560e+03]])
